Event Fabric API Client
=======================

.NET implementation of Event Fabric API to send events. It was developed in Mono 2.10.8.1 using MonoDevelop 3.0.3.2, but is perfectly compatible with .NET and Visual Studio.

Setup
-----

Usage
-----

see examples folder for more examples.


License
-------

MIT
